### ISSUE TITLE
Hook needed for configuration dialogue

### ISSUE THREAD

**Issue by johanneswseitz** [gocd-contrib/notification-skeleton-plugin#1]
Hi and thanks for the nice skeleton! 👍 

While I was building my own plugin (to be open sourced soon) I noticed that when I want to execute inline JavaScript of my own, i.e. to manipulate the DOM of the configuration dialogue, there is no hook for me that tells me when the DOM is ready to be modified and the dialogue is being shown. I ended up doing a dirty dirty setTimeout until the DOM to be ready for manipulation, but I would very much like to do it the right way, with a hook.

I noticed that the ModalBox JavaScript library used to display the configuration form *does* support callbacks for when the Form is shown, but I cannot find a way to set my own code in this callback. Can you integrate a proper for plugins to execute their own JavaScript code in future versions of GoCD?

**Comment by ketan** [comment]
Could you log this bug at github.com/gocd/gocd/issues instead? I think this is a general problem with plugins.

Additionally, if you are familiar with how angular works, you should be able to simply inject a `<script/>` tag with the right bindings. Using something like jQuery to manipulate the view will most likely cause breakage because the the form uses a two-way databinding and not a form-submit.
